# Value Iteration

In [1]:
# Transition probabilities
p = {}
#p[s,a]={(r,s'):P(r,s'|s,a)}

p[(0,1)]={(-10,0):1}
p[(1,1)]={(-10,0):1}
p[(1,0)]={(-1,1):1}
p[(0,0)]={(0,0):0.95,(0,1):0.05}

# Possible states and actions
states = [0,1]
actions = [0,1]

In [2]:
def value_iteration(p,states,actions,gamma):
    # initialize state-value function as zeros
    V = {0: 0, 1: 0}
    counter = 0
    
    while True:
        counter += 1
        delta = 0
        for s in states:
            v = V[s]
            values = []
            for a in actions:
                for key, val in p[(s,a)].items():
                    value = 0
                    r = key[0]
                    s_next = key[1]
                value += val*(r+gamma*V[s_next])
                values.append(value)
            V[s] = max(values)  
            delta = max(delta, (v-V[s]))
            
        if delta < 0.001:
            print("Stopped at iteration",counter)
            break
    return V

In [3]:
value_iteration(p,states,actions,0.9)

Stopped at iteration 67


{0: -0.4495702477721416, 1: -9.991404955442832}

In [4]:
# Different gamma values
gammas = [0, 0.5, 0.9, 0.90008, 0.90009, 0.901, 0.91, 0.92, 1]

In [5]:
for g in gammas:
    print("gamma:", g)
    print("V:", value_iteration(p,states,actions,g),"\n")

gamma: 0
Stopped at iteration 2
V: {0: 0.0, 1: -1} 

gamma: 0.5
Stopped at iteration 11
V: {0: -0.049951171875000006, 1: -1.9990234375} 

gamma: 0.9
Stopped at iteration 67
V: {0: -0.4495702477721416, 1: -9.991404955442832} 

gamma: 0.90008
Stopped at iteration 67
V: {0: -0.4499676549607499, 1: -9.999353099214998} 

gamma: 0.90009
Stopped at iteration 67
V: {0: -0.45001737454686463, 1: -10.000347490937292} 

gamma: 0.901
Stopped at iteration 68
V: {0: -0.45462917678418, 1: -10.0925835356836} 

gamma: 0.91
Stopped at iteration 32
V: {0: -0.4746497424883897, 1: -10.431931265664435} 

gamma: 0.92
Stopped at iteration 24
V: {0: -0.48031824121772176, 1: -10.441892781920304} 

gamma: 1
Stopped at iteration 14
V: {0: -0.5263125, 1: -10.5263125} 



When gamma is increased from 0.90008 to 0.90009, it no longer matters if you repair or not.